name       : python-pylibacl
version    : 0.5.3
release    : 1
source     :
    - http://pylibacl.k1024.org/downloads/pylibacl-0.5.3.tar.gz : 40be9f1fc5de05e4c25505c45ad7cda61b3b8db5dd730e98b6d2c05574e07d30
license    : LGPL-2.1
component  : programming.python
summary    : A python extension module that allows you to manipulate the POSIX.1e ACLs.
description: |
    This is a Python 2.4+ extension module allows you to manipulate the POSIX.1e Access Control Lists present in some OS/file-systems combinations.
builddeps  :
    - acl-devel
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
