name       : python-pylibacl
version    : 0.5.4
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/p/pylibacl/pylibacl-0.5.4.tar.gz : 060f375aeff90a16fbc3a827b7e234694ad636485d8ecd6654e01e1fc4ea3b37
homepage   : https://pylibacl.k1024.org/
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A python extension module that allows you to manipulate the POSIX.1e ACLs
description: |
    This is a C extension module for Python which implements POSIX ACLs manipulation. It is a wrapper on top of the systems's acl C library - see acl(5).
builddeps  :
    - pkgconfig(libacl)
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
